FROM python:3.11-slim-bookworm as requirements-stage

WORKDIR /tmp

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock* /tmp/

ENV POETRY_VIRTUALENVS_CREATE=false

RUN poetry lock --no-cache

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev


FROM python:3.11-slim-bookworm as build-stage

COPY --from=requirements-stage /tmp/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser
USER appuser
WORKDIR /home/appuser

ENV PATH="/home/appuser/.local/bin:${PATH}"

COPY --chown=appuser:appuser . .

LABEL maintainer="Paulo Marvin <paulo.marving@gmail.com>" \
    description="FastAPI Server" \
    version="1.0"

ENV SERVER_PORT=8000
ENV SERVER_HOST=0.0.0.0

EXPOSE $SERVER_PORT

CMD uvicorn app.main:app --host $SERVER_HOST --port $SERVER_PORT